/* eslint-disable */
import * as types from "./graphql";
import { TypedDocumentNode as DocumentNode } from "@graphql-typed-document-node/core";

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
  "\n  mutation LoginMutation($input: ObtainJSONWebTokenInput!) {\n    tokenAuth(input: $input){\n      token\n      payload\n      refreshExpiresIn\n      user {\n        id\n        email\n        fullName\n        role\n        isCollector\n        isAdmin\n        isClient\n      }\n    }\n  }\n": typeof types.LoginMutationDocument;
  "\n  query Me {\n    me {\n      id\n      email\n      fullName\n      isActive\n    }\n  }\n": typeof types.MeDocument;
  "\n  mutation CreateClient($input: CreateClientInput!) {\n    createClient(input: $input) {\n      user {\n        id\n        email\n        fullName\n        phoneNumber1\n        phoneNumber2\n        isActive\n      }\n    }\n  }\n": typeof types.CreateClientDocument;
  "\n  mutation UpdateClient($input: UpdateClientInput!) {\n    updateClient(input: $input) {\n      user {\n        id\n        email\n        fullName\n        phoneNumber1\n        phoneNumber2\n        isActive\n      }\n    }\n  }\n": typeof types.UpdateClientDocument;
  "\n  mutation CreatePayment($input: CreatePaymentInput!) {\n    createPayment(input: $input) {\n      payment {\n        id\n        amount\n        paymentDate\n        paymentMethod\n        notes\n        isVoided\n        createdAt\n        updatedAt\n        loan {\n          id\n          totalPaid\n          pendingBalance\n          isFullyPaid\n          status\n        }\n      }\n    }\n  }\n": typeof types.CreatePaymentDocument;
  "\n  query LoanDetail($id: ID!) {\n    loan(id: $id) {\n      id\n      amount\n      interestRate\n      installments\n      paymentFrequency\n      isApproved\n      isRejected\n      isFullyPaid\n      isOverdue\n      daysOverdue\n      dueDate\n      createdAt\n      updatedAt\n      totalAmount\n      totalPaid\n      pendingBalance\n      status\n      client {\n        id\n        user {\n          id\n          fullName\n          phoneNumber1\n          phoneNumber2\n        }\n        alias\n        addressLine1\n        addressLine2\n        neighborhood\n      }\n      route {\n        id\n        name\n        city {\n          id\n          name\n        }\n      }\n    }\n  }\n": typeof types.LoanDetailDocument;
  "\n  query LoansByClient($clientId: String!, $first: Int, $after: String) {\n    loansByClient(clientId: $clientId, first: $first, after: $after) {\n      edges {\n        node {\n          id\n          amount\n          interestRate\n          installments\n          paymentFrequency\n          isApproved\n          isRejected\n          isFullyPaid\n          isOverdue\n          daysOverdue\n          dueDate\n          createdAt\n          updatedAt\n          totalAmount\n          totalPaid\n          pendingBalance\n          status\n          route {\n            id\n            name\n            city {\n              id\n              name\n            }\n          }\n          payments {\n            id\n            amount\n            paymentDate\n            paymentMethod\n            notes\n            isVoided\n            createdAt\n          }\n        }\n      }\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n    }\n  }\n": typeof types.LoansByClientDocument;
  "\n  query LoansByCollector($collectorId: String, $first: Int, $after: String) {\n    loansByCollector(collectorId: $collectorId, first: $first, after: $after) {\n      edges {\n        node {\n          id\n          amount\n          interestRate\n          installments\n          paymentFrequency\n          isApproved\n          isRejected\n          isFullyPaid\n          isOverdue\n          daysOverdue\n          dueDate\n          createdAt\n          updatedAt\n          totalAmount\n          totalPaid\n          pendingBalance\n          status\n          client {\n            id\n            user {\n              id\n              fullName\n            }\n            alias\n            addressLine1\n            neighborhood\n            isActive\n          }\n          route {\n            id\n            name\n            city {\n              id\n              name\n            }\n          }\n        }\n      }\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n    }\n  }\n": typeof types.LoansByCollectorDocument;
  "\n  query LoansByRoute($routeId: String!, $first: Int, $after: String) {\n    loansByRoute(routeId: $routeId, first: $first, after: $after) {\n      edges {\n        node {\n          id\n          amount\n          interestRate\n          installments\n          paymentFrequency\n          isApproved\n          isRejected\n          isFullyPaid\n          isOverdue\n          daysOverdue\n          dueDate\n          createdAt\n          updatedAt\n          totalAmount\n          totalPaid\n          pendingBalance\n          status\n          client {\n            id\n            user {\n              id\n              fullName\n            }\n            alias\n            addressLine1\n            neighborhood\n            isActive\n            collector {\n              id\n              user {\n                id\n                fullName\n              }\n            }\n          }\n          route {\n            id\n            name\n          }\n        }\n      }\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n    }\n  }\n": typeof types.LoansByRouteDocument;
  "\n  query OverdueLoans($first: Int, $after: String) {\n    overdueLoans(first: $first, after: $after) {\n      edges {\n        node {\n          id\n          amount\n          interestRate\n          installments\n          paymentFrequency\n          isApproved\n          isFullyPaid\n          isOverdue\n          daysOverdue\n          dueDate\n          createdAt\n          totalAmount\n          totalPaid\n          pendingBalance\n          client {\n            id\n            user {\n              id\n              fullName\n              phoneNumber1\n              phoneNumber2\n            }\n            alias\n            addressLine1\n            neighborhood\n          }\n          route {\n            id\n            name\n            city {\n              id\n              name\n            }\n          }\n        }\n      }\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n    }\n  }\n": typeof types.OverdueLoansDocument;
  "\n  query PaymentsByLoan($loanId: String!, $first: Int, $after: String) {\n    paymentsByLoan(loanId: $loanId, first: $first, after: $after) {\n      edges {\n        node {\n          id\n          amount\n          paymentDate\n          paymentMethod\n          notes\n          isVoided\n          voidedAt\n          voidReason\n          createdAt\n          updatedAt\n          loan {\n            id\n            client {\n              id\n              user {\n                id\n                fullName\n              }\n            }\n          }\n        }\n      }\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n    }\n  }\n": typeof types.PaymentsByLoanDocument;
  "\n  query Cities($searchNames_Icontains: String){\n    cities(searchNames_Icontains: $searchNames_Icontains){\n      edges{\n        node{\n          id\n          name\n          region{\n            name\n          }\n        }\n      }\n    }\n  }\n": typeof types.CitiesDocument;
  "\n  query RouteById($id: String!){\n    route(id: $id){\n      id\n      name\n      startingBalance\n      city {\n        id\n        name\n      }\n      administrators{\n        edges {\n          node {\n            id\n            user{\n              id\n              fullName\n              isActive\n            }\n          }\n        }\n      }\n      collector {\n        id\n        user {\n          id\n          fullName\n          isActive\n        }\n      }\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.RouteByIdDocument;
  "\n  query RouteDetail($id: String!) {\n    route(id: $id) {\n      id\n      name\n      startingBalance\n      currentBalance\n      createdAt\n      updatedAt\n      city {\n        id\n        name\n        region {\n          id\n          name\n        }\n      }\n      collector {\n        id\n        user {\n          id\n          fullName\n          phoneNumber1\n        }\n      }\n      manager {\n        id\n        user {\n          id\n          fullName\n          phoneNumber1\n        }\n      }\n      administrators {\n        edges {\n          node {\n            id\n            user {\n              id\n              fullName\n            }\n          }\n        }\n      }\n      loansCount\n      pendingLoansCount\n      transactions {\n        id\n        amount\n        transactionType\n        description\n        createdAt\n        maker {\n          id\n          fullName\n        }\n      }\n    }\n  }\n": typeof types.RouteDetailDocument;
  "\n  query RoutesByCollector($first: Int, $after: String) {\n    routesByCollector(first: $first, after: $after) {\n      edges {\n        node {\n          id\n          name\n          startingBalance\n          currentBalance\n          createdAt\n          updatedAt\n          city {\n            id\n            name\n            region {\n              id\n              name\n            }\n          }\n          manager {\n            id\n            user {\n              id\n              fullName\n              phoneNumber1\n            }\n          }\n          loansCount\n          pendingLoansCount\n        }\n      }\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n    }\n  }\n": typeof types.RoutesByCollectorDocument;
  "\n  query AllTransactions($first: Int, $after: String) {\n    transactions(first: $first, after: $after) {\n      edges {\n        node {\n          id\n          description\n          transactionType\n          amount\n          createdAt\n          updatedAt\n          maker {\n            id\n            fullName\n          }\n        }\n      }\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n    }\n  }\n": typeof types.AllTransactionsDocument;
  "\n    query TransactionsByRouteId($routeId: String){\n        transactions(routeId: $routeId){\n            edges {\n                node {\n                    id\n                    description\n                    transactionType\n                    amount\n                    createdAt\n                    updatedAt\n                }\n            }\n            pageInfo {\n                startCursor\n                endCursor\n                hasNextPage\n                hasPreviousPage\n            }\n        }\n    }\n": typeof types.TransactionsByRouteIdDocument;
};
const documents: Documents = {
  "\n  mutation LoginMutation($input: ObtainJSONWebTokenInput!) {\n    tokenAuth(input: $input){\n      token\n      payload\n      refreshExpiresIn\n      user {\n        id\n        email\n        fullName\n        role\n        isCollector\n        isAdmin\n        isClient\n      }\n    }\n  }\n":
    types.LoginMutationDocument,
  "\n  query Me {\n    me {\n      id\n      email\n      fullName\n      isActive\n    }\n  }\n":
    types.MeDocument,
  "\n  mutation CreateClient($input: CreateClientInput!) {\n    createClient(input: $input) {\n      user {\n        id\n        email\n        fullName\n        phoneNumber1\n        phoneNumber2\n        isActive\n      }\n    }\n  }\n":
    types.CreateClientDocument,
  "\n  mutation UpdateClient($input: UpdateClientInput!) {\n    updateClient(input: $input) {\n      user {\n        id\n        email\n        fullName\n        phoneNumber1\n        phoneNumber2\n        isActive\n      }\n    }\n  }\n":
    types.UpdateClientDocument,
  "\n  mutation CreatePayment($input: CreatePaymentInput!) {\n    createPayment(input: $input) {\n      payment {\n        id\n        amount\n        paymentDate\n        paymentMethod\n        notes\n        isVoided\n        createdAt\n        updatedAt\n        loan {\n          id\n          totalPaid\n          pendingBalance\n          isFullyPaid\n          status\n        }\n      }\n    }\n  }\n":
    types.CreatePaymentDocument,
  "\n  query LoanDetail($id: ID!) {\n    loan(id: $id) {\n      id\n      amount\n      interestRate\n      installments\n      paymentFrequency\n      isApproved\n      isRejected\n      isFullyPaid\n      isOverdue\n      daysOverdue\n      dueDate\n      createdAt\n      updatedAt\n      totalAmount\n      totalPaid\n      pendingBalance\n      status\n      client {\n        id\n        user {\n          id\n          fullName\n          phoneNumber1\n          phoneNumber2\n        }\n        alias\n        addressLine1\n        addressLine2\n        neighborhood\n      }\n      route {\n        id\n        name\n        city {\n          id\n          name\n        }\n      }\n    }\n  }\n":
    types.LoanDetailDocument,
  "\n  query LoansByClient($clientId: String!, $first: Int, $after: String) {\n    loansByClient(clientId: $clientId, first: $first, after: $after) {\n      edges {\n        node {\n          id\n          amount\n          interestRate\n          installments\n          paymentFrequency\n          isApproved\n          isRejected\n          isFullyPaid\n          isOverdue\n          daysOverdue\n          dueDate\n          createdAt\n          updatedAt\n          totalAmount\n          totalPaid\n          pendingBalance\n          status\n          route {\n            id\n            name\n            city {\n              id\n              name\n            }\n          }\n          payments {\n            id\n            amount\n            paymentDate\n            paymentMethod\n            notes\n            isVoided\n            createdAt\n          }\n        }\n      }\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n    }\n  }\n":
    types.LoansByClientDocument,
  "\n  query LoansByCollector($collectorId: String, $first: Int, $after: String) {\n    loansByCollector(collectorId: $collectorId, first: $first, after: $after) {\n      edges {\n        node {\n          id\n          amount\n          interestRate\n          installments\n          paymentFrequency\n          isApproved\n          isRejected\n          isFullyPaid\n          isOverdue\n          daysOverdue\n          dueDate\n          createdAt\n          updatedAt\n          totalAmount\n          totalPaid\n          pendingBalance\n          status\n          client {\n            id\n            user {\n              id\n              fullName\n            }\n            alias\n            addressLine1\n            neighborhood\n            isActive\n          }\n          route {\n            id\n            name\n            city {\n              id\n              name\n            }\n          }\n        }\n      }\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n    }\n  }\n":
    types.LoansByCollectorDocument,
  "\n  query LoansByRoute($routeId: String!, $first: Int, $after: String) {\n    loansByRoute(routeId: $routeId, first: $first, after: $after) {\n      edges {\n        node {\n          id\n          amount\n          interestRate\n          installments\n          paymentFrequency\n          isApproved\n          isRejected\n          isFullyPaid\n          isOverdue\n          daysOverdue\n          dueDate\n          createdAt\n          updatedAt\n          totalAmount\n          totalPaid\n          pendingBalance\n          status\n          client {\n            id\n            user {\n              id\n              fullName\n            }\n            alias\n            addressLine1\n            neighborhood\n            isActive\n            collector {\n              id\n              user {\n                id\n                fullName\n              }\n            }\n          }\n          route {\n            id\n            name\n          }\n        }\n      }\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n    }\n  }\n":
    types.LoansByRouteDocument,
  "\n  query OverdueLoans($first: Int, $after: String) {\n    overdueLoans(first: $first, after: $after) {\n      edges {\n        node {\n          id\n          amount\n          interestRate\n          installments\n          paymentFrequency\n          isApproved\n          isFullyPaid\n          isOverdue\n          daysOverdue\n          dueDate\n          createdAt\n          totalAmount\n          totalPaid\n          pendingBalance\n          client {\n            id\n            user {\n              id\n              fullName\n              phoneNumber1\n              phoneNumber2\n            }\n            alias\n            addressLine1\n            neighborhood\n          }\n          route {\n            id\n            name\n            city {\n              id\n              name\n            }\n          }\n        }\n      }\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n    }\n  }\n":
    types.OverdueLoansDocument,
  "\n  query PaymentsByLoan($loanId: String!, $first: Int, $after: String) {\n    paymentsByLoan(loanId: $loanId, first: $first, after: $after) {\n      edges {\n        node {\n          id\n          amount\n          paymentDate\n          paymentMethod\n          notes\n          isVoided\n          voidedAt\n          voidReason\n          createdAt\n          updatedAt\n          loan {\n            id\n            client {\n              id\n              user {\n                id\n                fullName\n              }\n            }\n          }\n        }\n      }\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n    }\n  }\n":
    types.PaymentsByLoanDocument,
  "\n  query Cities($searchNames_Icontains: String){\n    cities(searchNames_Icontains: $searchNames_Icontains){\n      edges{\n        node{\n          id\n          name\n          region{\n            name\n          }\n        }\n      }\n    }\n  }\n":
    types.CitiesDocument,
  "\n  query RouteById($id: String!){\n    route(id: $id){\n      id\n      name\n      startingBalance\n      city {\n        id\n        name\n      }\n      administrators{\n        edges {\n          node {\n            id\n            user{\n              id\n              fullName\n              isActive\n            }\n          }\n        }\n      }\n      collector {\n        id\n        user {\n          id\n          fullName\n          isActive\n        }\n      }\n      createdAt\n      updatedAt\n    }\n  }\n":
    types.RouteByIdDocument,
  "\n  query RouteDetail($id: String!) {\n    route(id: $id) {\n      id\n      name\n      startingBalance\n      currentBalance\n      createdAt\n      updatedAt\n      city {\n        id\n        name\n        region {\n          id\n          name\n        }\n      }\n      collector {\n        id\n        user {\n          id\n          fullName\n          phoneNumber1\n        }\n      }\n      manager {\n        id\n        user {\n          id\n          fullName\n          phoneNumber1\n        }\n      }\n      administrators {\n        edges {\n          node {\n            id\n            user {\n              id\n              fullName\n            }\n          }\n        }\n      }\n      loansCount\n      pendingLoansCount\n      transactions {\n        id\n        amount\n        transactionType\n        description\n        createdAt\n        maker {\n          id\n          fullName\n        }\n      }\n    }\n  }\n":
    types.RouteDetailDocument,
  "\n  query RoutesByCollector($first: Int, $after: String) {\n    routesByCollector(first: $first, after: $after) {\n      edges {\n        node {\n          id\n          name\n          startingBalance\n          currentBalance\n          createdAt\n          updatedAt\n          city {\n            id\n            name\n            region {\n              id\n              name\n            }\n          }\n          manager {\n            id\n            user {\n              id\n              fullName\n              phoneNumber1\n            }\n          }\n          loansCount\n          pendingLoansCount\n        }\n      }\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n    }\n  }\n":
    types.RoutesByCollectorDocument,
  "\n  query AllTransactions($first: Int, $after: String) {\n    transactions(first: $first, after: $after) {\n      edges {\n        node {\n          id\n          description\n          transactionType\n          amount\n          createdAt\n          updatedAt\n          maker {\n            id\n            fullName\n          }\n        }\n      }\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n    }\n  }\n":
    types.AllTransactionsDocument,
  "\n    query TransactionsByRouteId($routeId: String){\n        transactions(routeId: $routeId){\n            edges {\n                node {\n                    id\n                    description\n                    transactionType\n                    amount\n                    createdAt\n                    updatedAt\n                }\n            }\n            pageInfo {\n                startCursor\n                endCursor\n                hasNextPage\n                hasPreviousPage\n            }\n        }\n    }\n":
    types.TransactionsByRouteIdDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: "\n  mutation LoginMutation($input: ObtainJSONWebTokenInput!) {\n    tokenAuth(input: $input){\n      token\n      payload\n      refreshExpiresIn\n      user {\n        id\n        email\n        fullName\n        role\n        isCollector\n        isAdmin\n        isClient\n      }\n    }\n  }\n",
): (typeof documents)["\n  mutation LoginMutation($input: ObtainJSONWebTokenInput!) {\n    tokenAuth(input: $input){\n      token\n      payload\n      refreshExpiresIn\n      user {\n        id\n        email\n        fullName\n        role\n        isCollector\n        isAdmin\n        isClient\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: "\n  query Me {\n    me {\n      id\n      email\n      fullName\n      isActive\n    }\n  }\n",
): (typeof documents)["\n  query Me {\n    me {\n      id\n      email\n      fullName\n      isActive\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: "\n  mutation CreateClient($input: CreateClientInput!) {\n    createClient(input: $input) {\n      user {\n        id\n        email\n        fullName\n        phoneNumber1\n        phoneNumber2\n        isActive\n      }\n    }\n  }\n",
): (typeof documents)["\n  mutation CreateClient($input: CreateClientInput!) {\n    createClient(input: $input) {\n      user {\n        id\n        email\n        fullName\n        phoneNumber1\n        phoneNumber2\n        isActive\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: "\n  mutation UpdateClient($input: UpdateClientInput!) {\n    updateClient(input: $input) {\n      user {\n        id\n        email\n        fullName\n        phoneNumber1\n        phoneNumber2\n        isActive\n      }\n    }\n  }\n",
): (typeof documents)["\n  mutation UpdateClient($input: UpdateClientInput!) {\n    updateClient(input: $input) {\n      user {\n        id\n        email\n        fullName\n        phoneNumber1\n        phoneNumber2\n        isActive\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: "\n  mutation CreatePayment($input: CreatePaymentInput!) {\n    createPayment(input: $input) {\n      payment {\n        id\n        amount\n        paymentDate\n        paymentMethod\n        notes\n        isVoided\n        createdAt\n        updatedAt\n        loan {\n          id\n          totalPaid\n          pendingBalance\n          isFullyPaid\n          status\n        }\n      }\n    }\n  }\n",
): (typeof documents)["\n  mutation CreatePayment($input: CreatePaymentInput!) {\n    createPayment(input: $input) {\n      payment {\n        id\n        amount\n        paymentDate\n        paymentMethod\n        notes\n        isVoided\n        createdAt\n        updatedAt\n        loan {\n          id\n          totalPaid\n          pendingBalance\n          isFullyPaid\n          status\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: "\n  query LoanDetail($id: ID!) {\n    loan(id: $id) {\n      id\n      amount\n      interestRate\n      installments\n      paymentFrequency\n      isApproved\n      isRejected\n      isFullyPaid\n      isOverdue\n      daysOverdue\n      dueDate\n      createdAt\n      updatedAt\n      totalAmount\n      totalPaid\n      pendingBalance\n      status\n      client {\n        id\n        user {\n          id\n          fullName\n          phoneNumber1\n          phoneNumber2\n        }\n        alias\n        addressLine1\n        addressLine2\n        neighborhood\n      }\n      route {\n        id\n        name\n        city {\n          id\n          name\n        }\n      }\n    }\n  }\n",
): (typeof documents)["\n  query LoanDetail($id: ID!) {\n    loan(id: $id) {\n      id\n      amount\n      interestRate\n      installments\n      paymentFrequency\n      isApproved\n      isRejected\n      isFullyPaid\n      isOverdue\n      daysOverdue\n      dueDate\n      createdAt\n      updatedAt\n      totalAmount\n      totalPaid\n      pendingBalance\n      status\n      client {\n        id\n        user {\n          id\n          fullName\n          phoneNumber1\n          phoneNumber2\n        }\n        alias\n        addressLine1\n        addressLine2\n        neighborhood\n      }\n      route {\n        id\n        name\n        city {\n          id\n          name\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: "\n  query LoansByClient($clientId: String!, $first: Int, $after: String) {\n    loansByClient(clientId: $clientId, first: $first, after: $after) {\n      edges {\n        node {\n          id\n          amount\n          interestRate\n          installments\n          paymentFrequency\n          isApproved\n          isRejected\n          isFullyPaid\n          isOverdue\n          daysOverdue\n          dueDate\n          createdAt\n          updatedAt\n          totalAmount\n          totalPaid\n          pendingBalance\n          status\n          route {\n            id\n            name\n            city {\n              id\n              name\n            }\n          }\n          payments {\n            id\n            amount\n            paymentDate\n            paymentMethod\n            notes\n            isVoided\n            createdAt\n          }\n        }\n      }\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n    }\n  }\n",
): (typeof documents)["\n  query LoansByClient($clientId: String!, $first: Int, $after: String) {\n    loansByClient(clientId: $clientId, first: $first, after: $after) {\n      edges {\n        node {\n          id\n          amount\n          interestRate\n          installments\n          paymentFrequency\n          isApproved\n          isRejected\n          isFullyPaid\n          isOverdue\n          daysOverdue\n          dueDate\n          createdAt\n          updatedAt\n          totalAmount\n          totalPaid\n          pendingBalance\n          status\n          route {\n            id\n            name\n            city {\n              id\n              name\n            }\n          }\n          payments {\n            id\n            amount\n            paymentDate\n            paymentMethod\n            notes\n            isVoided\n            createdAt\n          }\n        }\n      }\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: "\n  query LoansByCollector($collectorId: String, $first: Int, $after: String) {\n    loansByCollector(collectorId: $collectorId, first: $first, after: $after) {\n      edges {\n        node {\n          id\n          amount\n          interestRate\n          installments\n          paymentFrequency\n          isApproved\n          isRejected\n          isFullyPaid\n          isOverdue\n          daysOverdue\n          dueDate\n          createdAt\n          updatedAt\n          totalAmount\n          totalPaid\n          pendingBalance\n          status\n          client {\n            id\n            user {\n              id\n              fullName\n            }\n            alias\n            addressLine1\n            neighborhood\n            isActive\n          }\n          route {\n            id\n            name\n            city {\n              id\n              name\n            }\n          }\n        }\n      }\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n    }\n  }\n",
): (typeof documents)["\n  query LoansByCollector($collectorId: String, $first: Int, $after: String) {\n    loansByCollector(collectorId: $collectorId, first: $first, after: $after) {\n      edges {\n        node {\n          id\n          amount\n          interestRate\n          installments\n          paymentFrequency\n          isApproved\n          isRejected\n          isFullyPaid\n          isOverdue\n          daysOverdue\n          dueDate\n          createdAt\n          updatedAt\n          totalAmount\n          totalPaid\n          pendingBalance\n          status\n          client {\n            id\n            user {\n              id\n              fullName\n            }\n            alias\n            addressLine1\n            neighborhood\n            isActive\n          }\n          route {\n            id\n            name\n            city {\n              id\n              name\n            }\n          }\n        }\n      }\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: "\n  query LoansByRoute($routeId: String!, $first: Int, $after: String) {\n    loansByRoute(routeId: $routeId, first: $first, after: $after) {\n      edges {\n        node {\n          id\n          amount\n          interestRate\n          installments\n          paymentFrequency\n          isApproved\n          isRejected\n          isFullyPaid\n          isOverdue\n          daysOverdue\n          dueDate\n          createdAt\n          updatedAt\n          totalAmount\n          totalPaid\n          pendingBalance\n          status\n          client {\n            id\n            user {\n              id\n              fullName\n            }\n            alias\n            addressLine1\n            neighborhood\n            isActive\n            collector {\n              id\n              user {\n                id\n                fullName\n              }\n            }\n          }\n          route {\n            id\n            name\n          }\n        }\n      }\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n    }\n  }\n",
): (typeof documents)["\n  query LoansByRoute($routeId: String!, $first: Int, $after: String) {\n    loansByRoute(routeId: $routeId, first: $first, after: $after) {\n      edges {\n        node {\n          id\n          amount\n          interestRate\n          installments\n          paymentFrequency\n          isApproved\n          isRejected\n          isFullyPaid\n          isOverdue\n          daysOverdue\n          dueDate\n          createdAt\n          updatedAt\n          totalAmount\n          totalPaid\n          pendingBalance\n          status\n          client {\n            id\n            user {\n              id\n              fullName\n            }\n            alias\n            addressLine1\n            neighborhood\n            isActive\n            collector {\n              id\n              user {\n                id\n                fullName\n              }\n            }\n          }\n          route {\n            id\n            name\n          }\n        }\n      }\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: "\n  query OverdueLoans($first: Int, $after: String) {\n    overdueLoans(first: $first, after: $after) {\n      edges {\n        node {\n          id\n          amount\n          interestRate\n          installments\n          paymentFrequency\n          isApproved\n          isFullyPaid\n          isOverdue\n          daysOverdue\n          dueDate\n          createdAt\n          totalAmount\n          totalPaid\n          pendingBalance\n          client {\n            id\n            user {\n              id\n              fullName\n              phoneNumber1\n              phoneNumber2\n            }\n            alias\n            addressLine1\n            neighborhood\n          }\n          route {\n            id\n            name\n            city {\n              id\n              name\n            }\n          }\n        }\n      }\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n    }\n  }\n",
): (typeof documents)["\n  query OverdueLoans($first: Int, $after: String) {\n    overdueLoans(first: $first, after: $after) {\n      edges {\n        node {\n          id\n          amount\n          interestRate\n          installments\n          paymentFrequency\n          isApproved\n          isFullyPaid\n          isOverdue\n          daysOverdue\n          dueDate\n          createdAt\n          totalAmount\n          totalPaid\n          pendingBalance\n          client {\n            id\n            user {\n              id\n              fullName\n              phoneNumber1\n              phoneNumber2\n            }\n            alias\n            addressLine1\n            neighborhood\n          }\n          route {\n            id\n            name\n            city {\n              id\n              name\n            }\n          }\n        }\n      }\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: "\n  query PaymentsByLoan($loanId: String!, $first: Int, $after: String) {\n    paymentsByLoan(loanId: $loanId, first: $first, after: $after) {\n      edges {\n        node {\n          id\n          amount\n          paymentDate\n          paymentMethod\n          notes\n          isVoided\n          voidedAt\n          voidReason\n          createdAt\n          updatedAt\n          loan {\n            id\n            client {\n              id\n              user {\n                id\n                fullName\n              }\n            }\n          }\n        }\n      }\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n    }\n  }\n",
): (typeof documents)["\n  query PaymentsByLoan($loanId: String!, $first: Int, $after: String) {\n    paymentsByLoan(loanId: $loanId, first: $first, after: $after) {\n      edges {\n        node {\n          id\n          amount\n          paymentDate\n          paymentMethod\n          notes\n          isVoided\n          voidedAt\n          voidReason\n          createdAt\n          updatedAt\n          loan {\n            id\n            client {\n              id\n              user {\n                id\n                fullName\n              }\n            }\n          }\n        }\n      }\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: "\n  query Cities($searchNames_Icontains: String){\n    cities(searchNames_Icontains: $searchNames_Icontains){\n      edges{\n        node{\n          id\n          name\n          region{\n            name\n          }\n        }\n      }\n    }\n  }\n",
): (typeof documents)["\n  query Cities($searchNames_Icontains: String){\n    cities(searchNames_Icontains: $searchNames_Icontains){\n      edges{\n        node{\n          id\n          name\n          region{\n            name\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: "\n  query RouteById($id: String!){\n    route(id: $id){\n      id\n      name\n      startingBalance\n      city {\n        id\n        name\n      }\n      administrators{\n        edges {\n          node {\n            id\n            user{\n              id\n              fullName\n              isActive\n            }\n          }\n        }\n      }\n      collector {\n        id\n        user {\n          id\n          fullName\n          isActive\n        }\n      }\n      createdAt\n      updatedAt\n    }\n  }\n",
): (typeof documents)["\n  query RouteById($id: String!){\n    route(id: $id){\n      id\n      name\n      startingBalance\n      city {\n        id\n        name\n      }\n      administrators{\n        edges {\n          node {\n            id\n            user{\n              id\n              fullName\n              isActive\n            }\n          }\n        }\n      }\n      collector {\n        id\n        user {\n          id\n          fullName\n          isActive\n        }\n      }\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: "\n  query RouteDetail($id: String!) {\n    route(id: $id) {\n      id\n      name\n      startingBalance\n      currentBalance\n      createdAt\n      updatedAt\n      city {\n        id\n        name\n        region {\n          id\n          name\n        }\n      }\n      collector {\n        id\n        user {\n          id\n          fullName\n          phoneNumber1\n        }\n      }\n      manager {\n        id\n        user {\n          id\n          fullName\n          phoneNumber1\n        }\n      }\n      administrators {\n        edges {\n          node {\n            id\n            user {\n              id\n              fullName\n            }\n          }\n        }\n      }\n      loansCount\n      pendingLoansCount\n      transactions {\n        id\n        amount\n        transactionType\n        description\n        createdAt\n        maker {\n          id\n          fullName\n        }\n      }\n    }\n  }\n",
): (typeof documents)["\n  query RouteDetail($id: String!) {\n    route(id: $id) {\n      id\n      name\n      startingBalance\n      currentBalance\n      createdAt\n      updatedAt\n      city {\n        id\n        name\n        region {\n          id\n          name\n        }\n      }\n      collector {\n        id\n        user {\n          id\n          fullName\n          phoneNumber1\n        }\n      }\n      manager {\n        id\n        user {\n          id\n          fullName\n          phoneNumber1\n        }\n      }\n      administrators {\n        edges {\n          node {\n            id\n            user {\n              id\n              fullName\n            }\n          }\n        }\n      }\n      loansCount\n      pendingLoansCount\n      transactions {\n        id\n        amount\n        transactionType\n        description\n        createdAt\n        maker {\n          id\n          fullName\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: "\n  query RoutesByCollector($first: Int, $after: String) {\n    routesByCollector(first: $first, after: $after) {\n      edges {\n        node {\n          id\n          name\n          startingBalance\n          currentBalance\n          createdAt\n          updatedAt\n          city {\n            id\n            name\n            region {\n              id\n              name\n            }\n          }\n          manager {\n            id\n            user {\n              id\n              fullName\n              phoneNumber1\n            }\n          }\n          loansCount\n          pendingLoansCount\n        }\n      }\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n    }\n  }\n",
): (typeof documents)["\n  query RoutesByCollector($first: Int, $after: String) {\n    routesByCollector(first: $first, after: $after) {\n      edges {\n        node {\n          id\n          name\n          startingBalance\n          currentBalance\n          createdAt\n          updatedAt\n          city {\n            id\n            name\n            region {\n              id\n              name\n            }\n          }\n          manager {\n            id\n            user {\n              id\n              fullName\n              phoneNumber1\n            }\n          }\n          loansCount\n          pendingLoansCount\n        }\n      }\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: "\n  query AllTransactions($first: Int, $after: String) {\n    transactions(first: $first, after: $after) {\n      edges {\n        node {\n          id\n          description\n          transactionType\n          amount\n          createdAt\n          updatedAt\n          maker {\n            id\n            fullName\n          }\n        }\n      }\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n    }\n  }\n",
): (typeof documents)["\n  query AllTransactions($first: Int, $after: String) {\n    transactions(first: $first, after: $after) {\n      edges {\n        node {\n          id\n          description\n          transactionType\n          amount\n          createdAt\n          updatedAt\n          maker {\n            id\n            fullName\n          }\n        }\n      }\n      pageInfo {\n        startCursor\n        endCursor\n        hasNextPage\n        hasPreviousPage\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: "\n    query TransactionsByRouteId($routeId: String){\n        transactions(routeId: $routeId){\n            edges {\n                node {\n                    id\n                    description\n                    transactionType\n                    amount\n                    createdAt\n                    updatedAt\n                }\n            }\n            pageInfo {\n                startCursor\n                endCursor\n                hasNextPage\n                hasPreviousPage\n            }\n        }\n    }\n",
): (typeof documents)["\n    query TransactionsByRouteId($routeId: String){\n        transactions(routeId: $routeId){\n            edges {\n                node {\n                    id\n                    description\n                    transactionType\n                    amount\n                    createdAt\n                    updatedAt\n                }\n            }\n            pageInfo {\n                startCursor\n                endCursor\n                hasNextPage\n                hasPreviousPage\n            }\n        }\n    }\n"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> =
  TDocumentNode extends DocumentNode<infer TType, any> ? TType : never;
